name: Variable test - pass value between steps

on:
  workflow_dispatch:

jobs:
  pass_env:
    runs-on: ubuntu-latest

    steps:
      - name: Set env variable
        id: my_step  
        run: echo "MY_VAR=Hello World" >> $GITHUB_ENV

      - name: Consume in step 2
        run: |
          echo "Value: $MY_VAR"

      - name: Consume in step 3
        run: |
          echo "Value: ${{ env.MY_VAR }}"

      - name: Consume in step 4
        run: |
          echo "Value: $LOCAL_VAR"
        env:
          LOCAL_VAR: ${{ env.MY_VAR }} 


  pass_output:
    runs-on: ubuntu-latest

    steps:
      - name: Set output variable
        id: my_step  
        run: echo "MY_VAR=Hello World" >> $GITHUB_OUTPUT

      - name: Consume in step 2 (not ok)
        run: |
          echo "Value: $MY_VAR"

      - name: Consume in step 3
        run: |
          echo "Value: ${{ steps.my_step.outputs.MY_VAR }}"

      - name: Consume output step 4
        run: |
          echo "Value: $LOCAL_VAR"
        env:
          LOCAL_VAR: ${{ steps.my_step.outputs.MY_VAR }}
