name: Variable test - pass value between steps

jobs:
  pass_env:
    runs-on: ubuntu-latest
    steps:
      - name: Set env variable
        run: echo "MY_VALUE=ABC" >> $GITHUB_ENV
      - name: Use environment variable directly
        run: echo "Value: $MY_VALUE"
