name: Variable test - pass value between jobs

on:
  workflow_dispatch:

jobs:  
  create_value:
    runs-on: ubuntu-latest
    outputs:
      job_value: ${{ steps.my_step.outputs.MY_VAR }}
    steps:
      - name: Set output variable
        id: my_step  
        run: echo "MY_VAR=Hello World" >> $GITHUB_OUTPUT

  consume_value:
    runs-on: ubuntu-latest
    needs: create_value
    steps:
      - name: Consume value 1
        run: |
          echo "Value: ${{ needs.create_value.outputs.job_value }}"

      - name: Consume value 2
        run: |
          echo "Value: $my_value"
        env:
          my_value: ${{ needs.create_value.outputs.job_value }}
